on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual run

jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
     
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
       
    - name: Install dependencies
      run: pip install -r requirements.txt
     
    - name: Run tests with pytest
      run: python -m pytest test_app.py -v
     
    - name: Run application
      run: python app.py
     
  security-scan:
    runs-on: ubuntu-latest
    needs: test  # Run after tests pass
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
     
    - name: Run security scan
      run: |
        echo "ðŸ” Running security checks..."
        echo "1. Checking for secrets..."
        echo "2. Checking dependencies..."
        echo "âœ… Security scan completed"
       
  build:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
     
    - name: Build process
      run: |
        echo "ðŸ—ï¸ Building application..."
        echo "Python version: $(python --version)"
        echo "Creating build artifact..."
       
        # Create a simple build output
        mkdir -p dist
        echo "Build successful at $(date)" > dist/build-info.txt
        echo "Commit: ${{ github.sha }}" >> dist/build-info.txt
       
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
